### ISSUE TITLE
Create a sprint

### ISSUE THREAD

**Issue by lucdef** [lucdef/scrum-toolbox#6]
## Description
As a scrum master i want to create a new sprint cycle 

## Work items

- [ ] Create a new page
- [ ] Creating a form with 2 date
- [ ] Required date fields
- [ ] Send the information into firestore

## Technical information
- Table name : SprintCycle
## Acceptance criteria

- [ ] I can create a new sprint by selecting a starting date and finish date
- [ ] I can't create a new sprint if i don't select a starting or ending date
